"""empty message

Revision ID: 07ecf6c4b1bd
Revises: 5a8c4762bc44
Create Date: 2022-04-23 10:27:24.148917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ecf6c4b1bd'
down_revision = '5a8c4762bc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showrooms', sa.Column('type', sa.Enum('active', 'inactive', name='showroomtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showrooms', 'type')
    # ### end Alembic commands ###
