"""empty message

Revision ID: 0a961c863bc4
Revises: 07ecf6c4b1bd
Create Date: 2022-04-23 10:28:47.915147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a961c863bc4'
down_revision = '07ecf6c4b1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('image_uz', sa.String(), nullable=True),
    sa.Column('image_ru', sa.String(), nullable=True),
    sa.Column('conditions_uz', sa.Text(), nullable=True),
    sa.Column('conditions_ru', sa.Text(), nullable=True),
    sa.Column('gifts_uz', sa.Text(), nullable=True),
    sa.Column('gifts_ru', sa.Text(), nullable=True),
    sa.Column('gifts_image_uz', sa.Text(), nullable=True),
    sa.Column('gifts_image_ru', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'stopped', 'deleted', name='competitionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_uz', sa.String(), nullable=True),
    sa.Column('image_ru', sa.String(), nullable=True),
    sa.Column('contact_uz', sa.Text(), nullable=True),
    sa.Column('contact_ru', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='contactstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('user_post_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('showrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_uz', sa.String(), nullable=True),
    sa.Column('image_ru', sa.String(), nullable=True),
    sa.Column('info_uz', sa.Text(), nullable=True),
    sa.Column('name_uz', sa.Text(), nullable=True),
    sa.Column('name_ru', sa.Text(), nullable=True),
    sa.Column('info_ru', sa.Text(), nullable=True),
    sa.Column('location_link', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='showroomstatus'), nullable=True),
    sa.Column('type', sa.Enum('active', 'inactive', name='showroomtype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=True),
    sa.Column('telegram_id', sa.BIGINT(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('accepted', 'unaccepted', 'disactive', 'deleted', name='userpoststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='userstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_post')
    op.drop_table('showrooms')
    op.drop_table('posts')
    op.drop_table('contacts')
    op.drop_table('competitions')
    # ### end Alembic commands ###
