"""empty message

Revision ID: 2c04fa5e1ee2
Revises: 0a961c863bc4
Create Date: 2022-04-23 10:46:47.908111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c04fa5e1ee2'
down_revision = '0a961c863bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
