"""empty message

Revision ID: 4a9dc7bbb310
Revises: b9263105754e
Create Date: 2022-04-04 12:39:21.752102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9dc7bbb310'
down_revision = 'b9263105754e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('telegram_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'telegram_id')
    # ### end Alembic commands ###
