"""empty message

Revision ID: 60f4de44ff86
Revises: c2ab7009b2a4
Create Date: 2022-04-04 16:04:59.144106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f4de44ff86'
down_revision = 'c2ab7009b2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('gifts_image_uz', sa.Text(), nullable=True))
    op.add_column('competitions', sa.Column('gifts_image_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'gifts_image_ru')
    op.drop_column('competitions', 'gifts_image_uz')
    # ### end Alembic commands ###
