"""empty message

Revision ID: 74b16d2dcf8f
Revises: d9f7148d8f47
Create Date: 2022-04-22 20:49:17.976467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b16d2dcf8f'
down_revision = 'd9f7148d8f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
