"""empty message

Revision ID: 836e3801de0e
Revises: 74b16d2dcf8f
Create Date: 2022-04-22 20:53:27.475124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836e3801de0e'
down_revision = '74b16d2dcf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
