"""empty message

Revision ID: 83b4d4f35ac0
Revises: 9f19ae9961cc
Create Date: 2022-04-07 16:39:26.610803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b4d4f35ac0'
down_revision = '9f19ae9961cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post', sa.Column('comp_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_post', 'comp_id')
    # ### end Alembic commands ###
