"""empty message

Revision ID: 8800d13666df
Revises: 98024362f956
Create Date: 2022-04-07 13:32:25.950668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8800d13666df'
down_revision = '98024362f956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('user_post_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'user_post_id')
    op.drop_table('user_post')
    # ### end Alembic commands ###
