"""empty message

Revision ID: 98024362f956
Revises: 60f4de44ff86
Create Date: 2022-04-05 14:08:59.248456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98024362f956'
down_revision = '60f4de44ff86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showrooms', sa.Column('name_uz', sa.Text(), nullable=True))
    op.add_column('showrooms', sa.Column('name_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showrooms', 'name_ru')
    op.drop_column('showrooms', 'name_uz')
    # ### end Alembic commands ###
