"""empty message

Revision ID: 9f19ae9961cc
Revises: 8800d13666df
Create Date: 2022-04-07 15:03:22.818189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f19ae9961cc'
down_revision = '8800d13666df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post', sa.Column('images', sa.JSON(), nullable=True))
    op.drop_column('user_post', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_post', 'images')
    # ### end Alembic commands ###
