"""empty message

Revision ID: d9f7148d8f47
Revises: 6f2a596e8237
Create Date: 2022-04-22 20:42:14.393211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f7148d8f47'
down_revision = '6f2a596e8237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
