"""empty message

Revision ID: e2a739cdec49
Revises: 83b4d4f35ac0
Create Date: 2022-04-22 19:39:48.338615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a739cdec49'
down_revision = '83b4d4f35ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
