"""empty message

Revision ID: eaaf1a678b3a
Revises: f40a59a0ddda
Create Date: 2022-04-23 10:48:26.356007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaaf1a678b3a'
down_revision = 'f40a59a0ddda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_uz', sa.String(), nullable=True),
    sa.Column('image_ru', sa.String(), nullable=True),
    sa.Column('info_uz', sa.Text(), nullable=True),
    sa.Column('name_uz', sa.Text(), nullable=True),
    sa.Column('name_ru', sa.Text(), nullable=True),
    sa.Column('info_ru', sa.Text(), nullable=True),
    sa.Column('location_link', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='showroomstatus'), nullable=True),
    sa.Column('type', sa.Enum('showroom', 'dealer', name='showroomtype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('competitions', sa.Column('status', sa.Enum('active', 'stopped', 'deleted', name='competitionstatus'), nullable=True))
    op.add_column('contacts', sa.Column('status', sa.Enum('active', 'inactive', name='contactstatus'), nullable=True))
    op.add_column('user_post', sa.Column('status', sa.Enum('accepted', 'unaccepted', 'disactive', 'deleted', name='userpoststatus'), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('active', 'inactive', name='userstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('user_post', 'status')
    op.drop_column('contacts', 'status')
    op.drop_column('competitions', 'status')
    op.drop_table('showrooms')
    # ### end Alembic commands ###
