"""empty message

Revision ID: f40a59a0ddda
Revises: 2c04fa5e1ee2
Create Date: 2022-04-23 10:47:53.937031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40a59a0ddda'
down_revision = '2c04fa5e1ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_uz', sa.String(), nullable=True),
    sa.Column('image_ru', sa.String(), nullable=True),
    sa.Column('info_uz', sa.Text(), nullable=True),
    sa.Column('name_uz', sa.Text(), nullable=True),
    sa.Column('name_ru', sa.Text(), nullable=True),
    sa.Column('info_ru', sa.Text(), nullable=True),
    sa.Column('location_link', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='showroomstatus'), nullable=True),
    sa.Column('type', sa.Enum('showroom', 'dealer', name='showroomtype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showrooms')
    # ### end Alembic commands ###
